config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
  	resources :attendances, only: [:new, :create, :index]
  	resources :event_pictures, only: [:create]
  end
  resources :users, only: [:show, :edit, :update] do
  	resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
  	resources :users, only: [:index, :destroy]
    resources :event_submissions, only: [:index, :update, :show]
    resources :events, only: [:index, :destroy]
  	root to: "admin#index"
  end
end

app/views/shared/_banner.html.erb
	<div class="jumbotron jumbotron-fluid" style="background-image: url('<%= img_url %>'); background-size: 100%;">
	  <div class="text-center">
	    <h1 class="display-4 text-light"> <%= title %> </h1>
	    <p class="text-secondary" style="width: 40%; margin-left: 30%"> <%= text %> </p>
	  </div>
	</div>

app/views/shared/_listevents.html.erb
<div class="list-group list-group-flush" style="margin-top: 5vh">

  	<% @events.each do |event| %>

    <a href="<%= event_path(event.id) %>" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"><span class="lead"><%= event.title %></span> <span><h1 style="display: inline;"><%= event.start_date.strftime("%d") %></h1><h4 style="display: inline;"><%= event.start_date.strftime(".%m.%Y") %></h4></span></a>

    <% end %>

</div>

app/views/shared/_listparticipants.html.erb
<div class="list-group list-group-flush" style="margin-top: 5vh">

	<% @participants.each do |participant| %>
    <a href="mailto:<%= participant.email %>" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      <span><img src="https://images.pexels.com/photos/555790/pexels-photo-555790.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="rounded-circle" width="60"></span>
        <span class="lead text-primary"><%= participant.email %></span>
        <span class="lead"><%= participant.first_name %> <%= participant.last_name.upcase %></span>
    </a>
    <% end %>

</div>

app/views/shared/_showevent.html.erb
<div class="row text-center" style="margin-top: 10vh">

      <div class="col-4">
        <% if @event.event_picture.attached? %>
            <%= image_tag @event.event_picture, alt: 'event_picture',:class => "img-fluid rounded" %>
        <% else %>
        <% end %>
      </div>

      <div class="col-8">
          <div class="jumbotron jumbotron-fluid rounded" style="word-wrap: break-word;">
            <div class="text-center">
              <h1><%= @event.title %></h1>
              <p class="lead">Organized by <%= link_to "#{@admin.first_name}", "mailto:#{@admin.email}", :class => "text-muted" %></p>
              <p class="lead"><a href="#" class="text-warning"><i class="fab fa-facebook-f"></i></a> &nbsp;
              <a href="#" class="text-warning"><i class="fab fa-twitter"></i></a> &nbsp;
              <a href="#" class="text-warning"><i class="fab fa-instagram"></i></a> &nbsp;
              <a href="#" class="text-warning"><i class="fab fa-youtube"></i></a> &nbsp;
              <a href="#" class="text-warning"><i class="fab fa-vimeo-v"></i></a> &nbsp;
              <a href="#" class="text-warning"><i class="fab fa-spotify"></i></a></p>
              <hr>
              <p class="lead text-left" style="padding: 5vh"><%= @event.description %></p>

              <% if  current_user == nil %>
                <%= link_to "JOIN THE EVENT !", new_event_attendance_path(params[:id]), :class => "btn btn-primary" %>
             <% elsif  current_user.is_admin?(@event) %>
                <%= link_to "EDIT", event_attendances_path(params[:id]), :class => "btn btn-primary" %>
             <% elsif  current_user.is_participant?(@event) %>
             <% else %>
                <%= link_to "JOIN THE EVENT !", new_event_attendance_path(params[:id]), :class => "btn btn-primary" %>
             <% end %>

            </div>
          </div>
      </div>

</div>

<div class="row text-center" style="margin-top: 5vh">

      <div class="col-4">
          <h1><span class="badge badge-secondary"><%= @event.location %></span></h1>
          <h5>Location</h5>
      </div>

      <div class="col-4">
          <h1><span class="badge badge-secondary"><%= @event.price%> €</span></h1>
          <h5>Price</h5>
      </div>

      <div class="col-4">
          <h1><span class="badge badge-secondary"><%= @attendances.count%></span></h1>
          <h5><% if @attendances.count <= 1 %>
        Participant
        <% else %>
        Participants
        <% end %></h5>
      </div>

  </div>


  <div class="row text-center" style="margin-top: 5vh">

      <div class="col-4">
          <h1><span class="badge badge-secondary"><%= @event.start_date.strftime("%d.%m.%Y") %></span></h1>
          <h5>Start Date</h5>
      </div>

      <div class="col-4">
          <h1><span class="badge badge-secondary"><%= @event.end_date.strftime("%d.%m.%Y") %></span></h1>
          <h5>End Date</h5>
      </div>

      <div class="col-4">
          <h1><span class="badge badge-secondary"><%= @event.duration %> min</span></h1>
          <h5>Duration</h5>
      </div>

</div>

app/views/shared/_threecards.html.erb
<div class="row justify-content-around">

    <div class="col-3">
      <div class="card border-secondary text-center" style="padding-top: 5vh">
        <div class="card-title"><h1 class="display-1 text-danger"><i class="<%= first_icon %>"></i></h1></div>
        <div class="card-body">
          <p><%= first_text %></p>
          <a href="<%= first_link %>" class="btn btn-outline-danger btn-sm">Find out more</a>
        </div>
      </div>
    </div>

    <div class="col-3">
      <div class="card border-secondary text-center" style="padding-top: 5vh">
        <div class="card-title"><h1 class="display-1 text-warning"><i class="<%= second_icon %>"></i></h1></div>
        <div class="card-body">
          <p><%= second_text %></p>
          <a href="<%= second_link %>" class="btn btn-outline-warning btn-sm">Find out more</a>
        </div>
      </div>
    </div>

    <div class="col-3">
      <div class="card border-secondary text-center" style="padding-top: 5vh">
        <div class="card-title"><h1 class="display-1 text-success"><i class="<%= third_icon %>"></i></h1></div>
        <div class="card-body">
          <p><%= third_text %></p>
          <a href="<%= third_link %>" class="btn btn-outline-success btn-sm">Find out more</a>
        </div>
      </div>
    </div>

  </div>