config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
  	resources :attendances, only: [:new, :create, :index]
  	resources :event_pictures, only: [:create]
  end
  resources :users, only: [:show, :edit, :update] do
  	resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
  	resources :users, only: [:index, :destroy]
    resources :event_submissions, only: [:index, :update, :show]
    resources :events, only: [:index, :destroy]
  	root to: "admin#index"
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :new_participant_send

	belongs_to :event
	belongs_to :participant, class_name: "User"

	def new_participant_send
		UserMailer.new_participant(self).deliver_now
	end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :index]
  before_action :auth_user, only: [:index]

  def new
    @event = Event.find(params[:event_id])
    @stripe_price = @event.price * 100
  end

  def create
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )

    Attendance.create(participant: current_user, event: Event.find(params[:event_id]), stripe_customer_id: customer.id)
    redirect_to event_path(params[:event_id])

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance_path(params[:event_id])
  end

  def index
  	@event = Event.find(params[:event_id])
  	@participations = Attendance.where(event_id: params[:event_id])
  	@participants = []
  	@participations.each do |participation|
  		@participants << User.find(participation.participant_id)
  	end
  end

  private

  def auth_user
    unless current_user.is_admin?(Event.find(params[:event_id]))
      redirect_to event_path(params[:event_id])
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/index.html.erb
<div class="container">

<div class="row justify-content-around" style="margin-top: 10vh">

	<div class="col-4">
		<div class="card">
		  <div class="card-body">
		    <h3><%= @event.title %></h3>
		    <br>
		    <p class="lora-regular"> Here you can check your reservations list, edit or delete your event and change its picture.</p>
		    <br>
		    <p class="text-right">
		    <%= link_to "Edit your event", edit_event_path(params[:event_id]), :class => "btn btn-outline-info" %><br><br>
		    <%= link_to "Delete your event", event_path(params[:event_id]), :class => "btn btn-outline-danger", :data => { :confirm => "Are you sure?" }, :method => "delete" %>
			</p>
		  </div>
		</div>
		<br>
		<div class="card">
  			<div class="card-body">

  		<h6 class="card-title">Change the event picture</h6>
                  <%= form_tag event_event_pictures_path(@event), multipart: true do %>
                  <div class="row">
                  	<div class="col">
                    <%= file_field_tag :event_picture, :class => "form-control-file" %>
                </div>
                <div class="col text-right">
                    <%= submit_tag "Update event picture !", :class => "btn btn-outline-info btn-sm" %>
                </div>
                </div>
                  <% end %>

              </div>
         </div>
	</div>

	<div class="col-6">
		<h3 class="text-right">Participants</h3>
		
		<%= render "shared/listparticipants", collection: @participants %>

	</div>

</div>


</div>

app/views/attendances/new.html.erb
<div class="container">

<div class="row justify-content-center text-center" style="margin-top: 10vh">
<div class="col-6">

<%= form_tag event_attendances_path(params[:event_id]), :method => :post do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <label class="amount">
      <span class="lora-regular">Your reservation for the event</span><br/>
      <h3 class="montserrat-light"><%= @event.title %></h3>
      <hr/>
      <span class="lora-regular">Amount to pay:</span><br/>
      	<span class="display-1"><%= @event.price %> €</span>
    </label>
  </article>

		  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="Your reservation for the event <%= @event.title %>"
		          data-amount="<%= @stripe_price %>"
              data-currency="eur"
		          data-locale="auto">
		  </script>


<% end %>
</div>
</div>

</div>