config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
  	resources :attendances, only: [:new, :create, :index]
  	resources :event_pictures, only: [:create]
  end
  resources :users, only: [:show, :edit, :update] do
  	resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
  	resources :users, only: [:index, :destroy]
    resources :event_submissions, only: [:index, :update, :show]
    resources :events, only: [:index, :destroy]
  	root to: "admin#index"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
        <span class="text-muted">Made with <i class="far fa-heart text-secondary"></i> by Maud Lévy & Antoine Vercoutère </span>
</footer>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoowEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="shortcut icon" href="http://mlav.land/favicon.ico" type="image/x-icon" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300,400,500,700" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-primary">
      <%= link_to "PooowEvent", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Create a new event!", new_event_path, :class => "nav-link montserrat-light" %>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          
          <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
              <% if current_user.admin == true %>
              <%= link_to "Dashboard", admins_root_path, :class => "btn btn-outline-dark" %>
              <% end %>
              <%= link_to "Your profile", user_path(current_user.id), :class => "btn btn-outline-dark" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn btn-outline-dark" %>
            </div>
          </li>

          <% else %>
          <li class="nav-item active">
            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
              <%= link_to "Log in", new_user_session_path, :class => "btn btn-outline-dark" %>
              <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-outline-dark" %>
            </div>
          </li>

          <% end %>

        </ul>
        
      </div>
    </nav>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class="row justify-content-center" style="margin-top: 5vh">
         <div class="col-md-8 col-sm-12">
            <div class="alert alert-primary alert-dismissible fade show border-0" role="alert">
              <%= notice %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
    </div>
<% end %>

<% if alert %>
		<div class="row justify-content-center" style="margin-top: 5vh">
         <div class="col-md-8 col-sm-12">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
  <%= render('layouts/header.html.erb') %> 

  <%= render('layouts/messages.html.erb') %>
  <%= yield %>

  <%= render('layouts/footer.html.erb') %>

      